POST http://localhost:8002/register
Content-Type: application/json

{
    "username": "username",
    "password": "pass",
    "email": "email@domain.net"
}

####

GET http://localhost:8002/password/email@domain.net


###

GET http://localhost:6969/password/email@domain.net
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJuYW1lIiwiaWF0IjoxNTgxMTA3OTQ2LCJleHAiOjE1ODExOTQzNDZ9.Ys1HQLJCTyJXeSnXSKKu_Bc5xB0x9_HDMuTDt0J1L4o




###
POST http://localhost:6969/register
Content-Type: application/json

{
    "username": "username",
    "password": "pass",
    "email": "email@domain.net"
}